runtime: nodejs18

instance_class: F2

env_variables: 
  BUCKET_NAME: "lucypher-gcp-bucket"

handlers:
- url: /(.*\.(ico|txt|json|map|css|js|woff|woff2|ttf|eot|svg|png|jpg|jpeg))$
  static_files: dist/lucypher/browser/\1
  upload: dist/lucypher/browser/(.*\.(ico|txt|json|map|css|js|woff|woff2|ttf|eot|svg|png|jpg|jpeg))$

- url: /.*
  static_files: dist/lucypher/browser/index.html
  upload: dist/lucypher/browser/index.html